CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
DECLARE M INT;
set M=N-1;
  RETURN (
      IFNULL((SELECT DISTINCT SALARY FROM EMPLOYEE ORDER BY SALARY DESC LIMIT M, 1), NULL)# Write your MySQL query statement below.
      
  );
END
